#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "Non-Telegram identity + Discord — credential setup (issues #618, #619, #622)"

# ── Stage 1: GitHub OAuth App (issue #618) ────────────────────────────────
stage "GitHub — OAuth App for sign-in"
say "This is a NEW OAuth App for login — separate from the existing GITHUB_TOKEN"
say "personal access token (that one's only used for repo-enrichment metadata"
say "lookups and must not be touched)."
ask DASHBOARD_URL_INPUT "Your deployed dashboard base URL (e.g. https://app.leondev.xyz):"
GITHUB_CALLBACK_URL="${DASHBOARD_URL_INPUT%/}/api/auth/github/callback"
open_url "https://github.com/settings/developers"
step "Click 'New OAuth App'."
step "Application name: Ownix"
step "Homepage URL: ${DASHBOARD_URL_INPUT}"
step "Authorization callback URL: ${GITHUB_CALLBACK_URL}"
step "Click 'Register application'."
step "On the app page, copy the Client ID."
ask GITHUB_OAUTH_CLIENT_ID "Paste the Client ID:"
step "Click 'Generate a new client secret' and copy it immediately (shown once)."
ask_secret GITHUB_OAUTH_CLIENT_SECRET "Paste the Client secret:"
write_env GITHUB_OAUTH_CLIENT_ID "$GITHUB_OAUTH_CLIENT_ID"
write_env GITHUB_OAUTH_CLIENT_SECRET "$GITHUB_OAUTH_CLIENT_SECRET"
write_env GITHUB_OAUTH_REDIRECT_URI "$GITHUB_CALLBACK_URL"
set_secret GITHUB_OAUTH_CLIENT_SECRET "$GITHUB_OAUTH_CLIENT_SECRET"
pause "Stage 1 done."

# ── Stage 2: Google OAuth client — login only (issue #619) ────────────────
stage "Google — OAuth client for sign-in (login-only)"
warn "Create a BRAND NEW client. Do NOT reuse the client behind"
warn "GOOGLE_OAUTH_CLIENT_ID — that one is scoped to drive.file + spreadsheets"
warn "for the export feature and must stay separate (ADR-0030 / ADR-0061)."
GOOGLE_LOGIN_CALLBACK_URL="${DASHBOARD_URL_INPUT%/}/api/auth/google/callback"
open_url "https://console.cloud.google.com/apis/credentials"
step "Click 'Create Credentials' → 'OAuth client ID'."
step "Application type: Web application."
step "Name: Ownix Login (to tell it apart from the export client at a glance)."
step "Authorized redirect URI: ${GOOGLE_LOGIN_CALLBACK_URL}"
step "Click 'Create'."
step "Copy the Client ID shown in the dialog."
ask GOOGLE_LOGIN_CLIENT_ID "Paste the Client ID:"
step "Copy the Client secret shown in the same dialog."
ask_secret GOOGLE_LOGIN_CLIENT_SECRET "Paste the Client secret:"
say "On the OAuth consent screen for this client, only request these scopes:"
say "openid, email, profile — nothing else. No drive/sheets scopes on this client."
write_env GOOGLE_LOGIN_CLIENT_ID "$GOOGLE_LOGIN_CLIENT_ID"
write_env GOOGLE_LOGIN_CLIENT_SECRET "$GOOGLE_LOGIN_CLIENT_SECRET"
write_env GOOGLE_LOGIN_REDIRECT_URI "$GOOGLE_LOGIN_CALLBACK_URL"
set_secret GOOGLE_LOGIN_CLIENT_SECRET "$GOOGLE_LOGIN_CLIENT_SECRET"
pause "Stage 2 done."

# ── Stage 3: Discord bot application (issue #622) ─────────────────────────
stage "Discord — bot application for the DM channel"
open_url "https://discord.com/developers/applications"
step "Click 'New Application', name it Ownix, accept the ToS, click 'Create'."
step "On the General Information page, copy the Application ID."
ask DISCORD_APPLICATION_ID "Paste the Application ID:"
step "Go to the 'Bot' tab in the left sidebar."
step "Click 'Reset Token' (or 'Add Bot' first if this is a fresh app), confirm,"
step "  then copy the bot token immediately (shown once)."
ask_secret DISCORD_BOT_TOKEN "Paste the bot token:"
warn "Leave 'Message Content Intent' OFF on this page. DMs already deliver"
warn "content without it (Discord's docs carve DMs out of that privileged"
warn "intent) — turning it on only forces an app-verification review once"
warn "past 100 servers, which the DM-only design (ADR-0061) deliberately avoids."
say "A user needs to share a server with the bot before they can open a DM"
say "with it, so it needs to live in at least one server (e.g. a small"
say "'Ownix' server your early users join)."
open_url "https://discord.com/developers/applications/${DISCORD_APPLICATION_ID}/oauth2/url-generator"
step "Under OAuth2 → URL Generator: check the 'bot' scope only, no permissions"
step "  needed (this bot only sends/receives DMs)."
step "Copy the generated URL, open it, and add the bot to one server you control."
pause "Added the bot to a server?"
write_env DISCORD_APPLICATION_ID "$DISCORD_APPLICATION_ID"
write_env DISCORD_BOT_TOKEN "$DISCORD_BOT_TOKEN"
set_secret DISCORD_BOT_TOKEN "$DISCORD_BOT_TOKEN"
pause "Stage 3 done."

finish
note "GitHub  → GITHUB_OAUTH_CLIENT_ID / GITHUB_OAUTH_CLIENT_SECRET / GITHUB_OAUTH_REDIRECT_URI"
note "Google  → GOOGLE_LOGIN_CLIENT_ID / GOOGLE_LOGIN_CLIENT_SECRET / GOOGLE_LOGIN_REDIRECT_URI"
note "Discord → DISCORD_APPLICATION_ID / DISCORD_BOT_TOKEN"
note "None of these overwrite GITHUB_TOKEN or GOOGLE_OAUTH_* (export) — check with:"
note "  grep -E '^(GITHUB_TOKEN|GOOGLE_OAUTH_CLIENT_ID)=' \"$ENV_FILE\""
