#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ZONE="leondev.xyz"
CONTACT_LOCAL="contact.me"
WORKER_NAME="ownix-email-digest"
EMAIL_ROUTING_URL="https://dash.cloudflare.com/?to=/:account/$ZONE/email/routing/routes"
DESTINATIONS_URL="https://dash.cloudflare.com/?to=/:account/$ZONE/email/routing/destination-addresses"
WORKERS_URL="https://dash.cloudflare.com/?to=/:account/workers/services/view/$WORKER_NAME"

banner "Retire inbound email routing ($ZONE)"

# ── 1. Catch-all first ────────────────────────────────────────────────────
stage "Delete the catch-all rule"
say "ADR-0060 replaced inbound mail with public-archive polling, so the"
say "catch-all that fed the $WORKER_NAME Worker has to go."
say ""
say "This is FIRST on purpose: the API route it posts to (/webhook/email-digest)"
say "is already deleted, so every message the catch-all accepts right now is"
say "handed to a Worker that fails. Removing the rule before the Worker means"
say "there is never a window where mail is accepted and then black-holed."
open_url "$EMAIL_ROUTING_URL"
step "Open the 'Routing rules' tab."
step "Find the catch-all row (Custom address: *@$ZONE → Send to a Worker)."
step "Use the row's ⋯ menu → Delete, or toggle catch-all off."
if confirm "Catch-all deleted (or already gone)?"; then
  note "catch-all cleared"
else
  SKIPPED+=("Delete the Email Routing catch-all rule for $ZONE")
  warn "left in place — mail to $ZONE will keep hitting a dead Worker"
fi
pause

# ── 2. The Worker ─────────────────────────────────────────────────────────
stage "Delete the $WORKER_NAME Worker"
say "The Worker parsed inbound MIME and POSTed it to the API with a shared"
say "secret. Both ends are gone from the repo, so deleting it also disposes of"
say "the OWNIX_EMAIL_SECRET binding — one less live credential to rotate."
say ""
say "If you prefer the CLI: cd into a checkout of the old ops/email-worker and"
say "run 'npx wrangler delete'. The directory is deleted on this branch, so the"
say "dashboard is usually the easier path now."
open_url "$WORKERS_URL"
step "Settings → scroll to the bottom → Delete."
step "Confirm by typing the Worker name when prompted."
if confirm "Worker deleted (or already gone)?"; then
  note "worker removed"
else
  SKIPPED+=("Delete the Cloudflare Worker $WORKER_NAME")
fi
pause

# ── 3. Destination address ────────────────────────────────────────────────
stage "Verify the destination inbox"
say "Forwarding only works to an address Cloudflare has verified. This was"
say "likely done during the original setup, but it costs nothing to confirm."
open_url "$DESTINATIONS_URL"
step "Check your personal inbox is listed with status 'Verified'."
step "If it is missing: 'Add destination address' → enter it → open the"
step "  confirmation email Cloudflare sends → click the verify link."
ask CONTACT_DESTINATION "Which verified inbox should mail forward to?"
if [[ -z "$CONTACT_DESTINATION" ]]; then
  SKIPPED+=("Record the destination inbox for $CONTACT_LOCAL@$ZONE")
  warn "no destination recorded — stage 4 still needs one"
fi
pause

# ── 4. The PO box ─────────────────────────────────────────────────────────
stage "Create $CONTACT_LOCAL@$ZONE"
say "A SPECIFIC address, not a catch-all. Two reasons that matters:"
say "  • Catch-all domains are what third-party signup validators reject —"
say "    one of the two walls that killed the #607 alias approach."
say "  • A catch-all collects spam for every address anyone guesses."
say ""
say "This replaces your personal Gmail on the privacy, terms and accessibility"
say "pages, so the address is about to become public. That is the point of a"
say "PO box — but it is also why it should forward, not be a real mailbox."
open_url "$EMAIL_ROUTING_URL"
step "Routing rules → 'Create address'."
step "Custom address: $CONTACT_LOCAL   Domain: $ZONE"
step "Action: 'Send to an email' → ${CONTACT_DESTINATION:-your verified inbox}"
step "Save."
if confirm "Rule for $CONTACT_LOCAL@$ZONE created?"; then
  write_env OWNIX_CONTACT_EMAIL "$CONTACT_LOCAL@$ZONE"
  note "recorded for the mailto: swap on the legal pages"
else
  SKIPPED+=("Create the $CONTACT_LOCAL@$ZONE routing rule")
fi
pause

# ── 5. Drop the dead secret ───────────────────────────────────────────────
stage "Remove EMAIL_WEBHOOK_SECRET from the API env"
say "src/config.py no longer declares this field. Pydantic is configured with"
say "extra='ignore', so a leftover line is inert rather than fatal — but it is"
say "a live shared secret for a webhook that no longer exists."
say ""
if [[ -f .env ]] && grep -qE '^EMAIL_WEBHOOK_SECRET=' .env; then
  step "Found EMAIL_WEBHOOK_SECRET in ./.env"
  if confirm "Remove that line now?"; then
    tmp=$(mktemp)
    grep -vE '^EMAIL_WEBHOOK_SECRET=' .env > "$tmp" && mv "$tmp" .env
    note "removed from .env — restart the api/worker containers to pick it up"
  else
    SKIPPED+=("Remove EMAIL_WEBHOOK_SECRET from .env")
  fi
else
  note "not present in ./.env — nothing to remove"
fi
step "Also check any other place the API's env is set (host .env, systemd unit,"
step "  or your compose override) and drop it there too."
pause

# ── 6. Prove it ───────────────────────────────────────────────────────────
stage "Verify"
say "Two checks — the second is the one people forget."
say ""
step "1. Send a test mail to $CONTACT_LOCAL@$ZONE from any account."
step "   It should land in ${CONTACT_DESTINATION:-your inbox} within a minute."
step "2. Send one to something random, e.g. zzz-test-$RANDOM@$ZONE."
step "   It MUST bounce. If it is delivered, the catch-all is still active"
step "   and stage 1 did not take."
say ""
if confirm "Test address delivers AND the random address bounces?"; then
  note "inbound mail retired; $CONTACT_LOCAL@$ZONE is live"
else
  SKIPPED+=("Re-check Email Routing — verification did not pass")
  warn "do not update the legal pages until the forward actually works"
fi

finish
